targets:
  $default:
    builders:
      drift_dev:
        options:
          sql:
            dialect: sqlite
          named_parameters: true
          apply_converters_on_variables: true
          generate_values_in_copy_with: true
